name: 'build-project'
description: 'Build project with latest Godot editor from V-Sekai/world-godot'
inputs:
  godot_rev:
    description: 'Godot editor build'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
