name: 'build-project'
description: 'Build project with latest Godot editor from V-Sekai/world-godot'
inputs:
  nightly:
    description: 'Nightly build mode'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
