name: Automated Tagging
on:
  schedule:
    - cron: "00 12 */3 * *"

jobs:
  test_commit:
    name: Test schedule
    runs-on: ubuntu-latest
    steps:
      - name: Set timestamp
        id: timestamp
        run: |
          LAST_TIMESTAMP="$(git log -1 --format=%ct)"
          echo "${LAST_TIMESTAMP}" >>> ${GITHUB_OUTPUT}

      - name: Check Timestamp
        id: check-timestamp
        uses: actions/cache@v1
        with:
          path: last-timestamp
          key: last-timestamp-${{ github.sha }}

      - name: Cache check
        if: steps.check-timestamp.outputs.cache-hit != 'true'
        run: echo "TAG_PUSH=true" >>> ${GITHUB_OUTPUT}

      - name: Create cache file
        run: |
          rm -r last-timestamp
          mkdir last-timestamp
          LAST_TIMESTAMP="$(git log -1 --format=%ct)"
          echo "${LAST_TIMESTAMP}" > timestamp.txt

  tag:
    runs-on: ubuntu-latest
    #needs: check-timestamp
    steps:
      - name: Check last commit
        run: |
          LAST_COMMIT="$(git log -1 --format=%ct)"
      - uses: actions/checkout@v2
      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
          git push origin "v${{ github.run_number }}"

