name: Build Platform Target

on:
  repository_dispatch:
    types: ['build-ready']
  push:
    branches: ['gh-test']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Set env
        run: |
          echo "GITHUB_REV=${{ github.event.repository.name }}" >> "$GITHUB_ENV"

      - name: Test
        run: |
          echo "Github event -  ${GITHUB_REV}"
          touch test.txt
          echo "Github event -  ${{ github.event.client_payload.commit_sha }}"

      #- name: Docker build project
        #uses: ./docker/build-project
       # with:
         # godot_rev: ${{ github.event.client_payload.commit_sha }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: v-sekai-release
          path: ${{ github.workspace }}
