name: Build Platform Target

on:
  push:
    branches: [action]
env:
  BIN: 'release/bin/'
  BUILD_ARGS: '--headless'
  BUILD_PLATFORMS: ('Linux')
  GODOT_REPO: 'V-Sekai/world-godot'
  GODOT_ZIP: 'v-sekai-world.zip'
  GODOT_EDITOR: 'godot.linuxbsd.editor.double.x86_64'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Set env
        run: |
          echo "TEMPLATE_DIR=${HOME}/.local/share/godot/export_templates" >> "$GITHUB_ENV"
          mkdir -p src

      - name: Checkout  
        uses: actions/checkout@v4
        with:
          path: 'src'

      - name: Download Godot
        run: |
          pwd
          tree -a .
          echo homee ${HOME}
          echo ~
          mkdir -p ${HOME}/myhome
          ls ${HOME}
          echo Template dir ${TEMPLATE_DIR}
          mkdir -p ${TEMPLATE_DIR}
          cd ${TEMPLATE_DIR} && pwd
          tree -a ${HOME}
          echo 'home' && ls /home/
          ls -a ${TEMPLATE_DIR}
          tree -a ${TEMPLATE_DIR}
          FILE_URL=$( \
          curl -sS -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          https://api.github.com/repos/${GODOT_REPO}/releases \
          | jq -r '.[0].assets.[] | select(.name == env.GODOT_ZIP).browser_download_url' \
          )
          echo Downloading ${FILE_URL}
          curl -OL --url ${FILE_URL}
          echo ${GODOT_ZIP%.*}
          unzip ${GODOT_ZIP} && mv ${GODOT_ZIP%.*} godot
          tree -L 2 .
          mv godot ${HOME}/godot

      - name: Setup
        run: |
          mv ${HOME}/godot ./godot
          tree -L 2
          echo "./godot/${GODOT_EDITOR}"
          echo "./${GODOT_EDITOR}"
          stat "godot/${GODOT_EDITOR}"
          mv "./godot/${GODOT_EDITOR}" "./${GODOT_EDITOR}"
          chmod +x ${GODOT_EDITOR}

          GODOT_VERSION=$( ./${GODOT_EDITOR} --version | sed 's/\.[^.]*$//' )
          mkdir -p ${TEMPLATE_DIR}
          echo ${GODOT_VERSION} > "${TEMPLATE_DIR}/version.txt"

          mv godot/* ${TEMPLATE_DIR}/
          mkdir -p ${BIN}

      - name: Test
        run: |
          ls -a .
          ls -a '~/.local/share/godot/export_templates/'
          ls -a src
          tree -L 2 src
          tree ${BIN}

      - name: Build
        run: |
          for PLATFORM in ${BUILD_PLATFORMS}; do \
            echo 'Building ${PLATFORM}...' \
            ${GODOT_EDITOR} ${BUILD_ARGS} --path 'src' --export-release ${PLATFORM} ${BIN}/v-sekai_${PLATFORM} \
          done
          tree ${BIN}

  build:
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      actions: write
    steps:
      - name: Build
        run: |
          ls .


