name: Build Platform Target

on:
  push:
    branches: [action]
env:
  BIN: 'release/bin/'
  BUILD_ARGS: '--headless'
  BUILD_PLATFORMS: 'Linux,Linux1'
  GODOT_REPO: 'V-Sekai/world-godot'
  GODOT_ZIP: 'v-sekai-world.zip'
  GODOT_EDITOR: 'godot.linuxbsd.editor.double.x86_64'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Set env
        run: |
          #readarray -td ',' plats < <( echo -ne "${BUILD_PLATFORMS}")
          #for plat in "${plats[@]}"; do
          #    echo "plat${plat}plat"
          #done
          echo "TEMPLATE_DIR=${HOME}/.local/share/godot/export_templates" >> "$GITHUB_ENV"
          #echo "BUILD_PLATFORMS=('Linux')" >> "$GITHUB_ENV"
          mkdir -p src

      - name: Checkout  
        uses: actions/checkout@v4
        with:
          path: 'src'

      - name: Download Godot
        run: |
          
          sed -i -r "s|(^custom_template/[a-z]*=\")~|\1${HOME}|g" './src/export_presets.cfg'
          pwd
          tree -a .
          echo homee ${HOME}
          echo ~
          mkdir -p ${HOME}/myhome
          ls ${HOME}
          echo Template dir ${TEMPLATE_DIR}
          mkdir -p ${TEMPLATE_DIR}
          cd ${TEMPLATE_DIR} && pwd
          tree -a ${HOME}
          echo 'home' && ls /home/
          ls -a ${TEMPLATE_DIR}
          tree -a ${TEMPLATE_DIR}
          FILE_URL=$( \
          curl -sS -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          https://api.github.com/repos/${GODOT_REPO}/releases \
          | jq -r '.[0].assets.[] | select(.name == env.GODOT_ZIP).browser_download_url' \
          )
          echo Downloading ${FILE_URL}
          curl -OL --url ${FILE_URL}
          echo ${GODOT_ZIP%.*}
          unzip ${GODOT_ZIP} && mv ${GODOT_ZIP%.*} godot
          tree -L 2 .
          mv godot ${HOME}/godot

      - name: Setup
        run: |
          mv ${HOME}/godot ./godot
          tree -L 2
          echo "./godot/${GODOT_EDITOR}"
          echo "./${GODOT_EDITOR}"
          stat "godot/${GODOT_EDITOR}"
          mv "./godot/${GODOT_EDITOR}" "./${GODOT_EDITOR}"
          chmod +x ${GODOT_EDITOR}

          GODOT_VERSION=$( ./${GODOT_EDITOR} --version | sed 's/\.[^.]*$//' )
          mkdir -p ${TEMPLATE_DIR}
          echo ${GODOT_VERSION} > "${TEMPLATE_DIR}/version.txt"

          mv godot/* ${TEMPLATE_DIR}/
          sed -i -r "s|(^custom_template/[a-z]*=\")~|\1${HOME}|g" './src/export_presets.cfg'
          mkdir -p ${BIN}

          mkdir -p ${TEMPLATE_DIR}/${GODOT_VERSION}
          echo ${GODOT_VERSION} > "${TEMPLATE_DIR}/${GODOT_VERSION}/version.txt"
          cp "${TEMPLATE_DIR}/${GODOT_VERSION}/godot.linuxbsd.template_release.double.x86_64" \
            "${HOME}/.local/share/godot/export_templates/linux_release.x86_64"
            
          cp "${TEMPLATE_DIR}/godot.linuxbsd.template_debug.double.x86_64" \
            "${HOME}/.local/share/godot/export_templates/linux_debug.x86_64"

      - name: Test
        run: |
          tree ${TEMPLATE_DIR}
          cat './src/export_presets.cfg' | grep 'custom_template'
          ls -a .
          # ls -a '~/.local/share/godot/export_templates/'
          ls -a ${TEMPLATE_DIR}
          ls -a src
          tree -L 2 src
          tree ${BIN}

      - name: Build
        run: |
          pwd
          rm -rf './src/.godot'
          tree -aL 2
          tree -aL 2 ${HOME}
          chmod +x ${GODOT_EDITOR}

          # Open editor to fix missing files
          echo "Fix .godot import"
          ./${GODOT_EDITOR} --headless --import --build-solutions --path 'src' > /dev/null 2>&1

          tree -a -L 2 src

          readarray -td ',' PLATFORMS < <( echo -ne "${BUILD_PLATFORMS}")
          for PLATFORM in "${PLATFORMS[@]}"; do
            echo "Building ${PLATFORM}..."
            ./${GODOT_EDITOR} ${BUILD_ARGS} --path 'src' --export-release ${PLATFORM} ${BIN}/v-sekai_${PLATFORM} || true
          done
          tree -a ${BIN}

  build:
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      actions: write
    steps:
      - name: Build
        run: |
          ls .


