name: Build Platform Target

on:
  repository_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Set env
        run: |
          echo "GITHUB_REV=${{ github.event.repository.name }}" >> "$GITHUB_ENV"

      - name: Test
        run: |
          echo "Github event -  ${GITHUB_REV}"
          
          echo "Github event -  ${{ github.event.client_payload.commit_sha }}"
