name: Build Platform Target

on:
  push:
    branches: [action]
env:
  BIN: 'release/bin/'
  GODOT_REPO: 'V-Sekai/world-godot'
  GODOT_ZIP: 'v-sekai-world.zip'
  GODOT_EDITOR: 'godot.linuxbsd.editor.double.x86_64'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Download Godot
        run: |
          FILE_URL=$( \
          curl -sS -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          https://api.github.com/repos/${GODOT_REPO}/releases \
          | jq -r '.[0].assets.[] | select(.name == env.GODOT_ZIP).browser_download_url' \
          )
          echo Downloading ${FILE_URL}
          #curl -OL --url ${FILE_URL}
          unzip ${GODOT_ZIP}

      - name: Setup
        run: |
          chmod +x ${GODOT_EDITOR}
          GODOT_VERSION=$(${GODOT_EDITOR} --version | sed 's///')
          mkdir -p '~/.local/share/godot/export_templates/${GODOT_VERSION}'
          echo ${GODOT_VERSION} > '~/.local/share/godot/export_templates/${GODOT_VERSION}/version.txt'

          mkdir -p src

      - name: Checkout  
        uses: actions/checkout@v4
        with:
          path: 'src'
          
          
      - name: Checkout
        run: |
          ls -a .
          ls -a v-sekai-world
          ls -a '~/.local/share/godot/export_templates/'
