name: Build Platform Target

on:
  push:
    branches: [action]
env:
  BIN: 'release/bin/'
  GODOT_ZIP: 'v-sekai-world.zip'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout
        run: |
          mkdir -p src
          curl -sS -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          https://api.github.com/repos/V-Sekai/world-godot/releases \
          | jq '.[0].url.assets.name == ${GODOT_ZIP}'
          gh release download --pattern v-sekai-world.zip --repo V-Sekai/world-godot
          curl https://github.com/V-Sekai/world-godot/releases/latest/download/v-sekai-world.zip

      - name: Checkout  
        uses: actions/checkout@v4
        with:
          path: 'src'
          
      - name: Download Godot
        uses: actions/download-artifact@v4
        with:
          repository: V-Sekai/world-godot
          github-token: ${{ secrets.TOKEN_PAT2 }}
          
      - name: Checkout
        run: |
          ls -a .
