name: Build Platform Target

on:
  push:
    branches: [action]
env:
  BIN: '~/release/bin/'
  BUILD_ARGS: '--headless'
  BUILD_PLATFORMS: ('Linux', 'Windows', 'Mac')
  GODOT_REPO: 'V-Sekai/world-godot'
  GODOT_ZIP: 'v-sekai-world.zip'
  GODOT_EDITOR: 'godot.linuxbsd.editor.double.x86_64'
  TEMPLATE_DIR: '~/.local/share/godot/export_templates'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
defaults:
  run:
    working-directory: '~/godot'

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Download Godot
        run: |
          pwd
          tree -a .
          FILE_URL=$( \
          curl -sS -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          https://api.github.com/repos/${GODOT_REPO}/releases \
          | jq -r '.[0].assets.[] | select(.name == env.GODOT_ZIP).browser_download_url' \
          )
          echo Downloading ${FILE_URL}
          #curl -OL --url ${FILE_URL}
          unzip ${GODOT_ZIP}

      - name: Setup
        run: |
          chmod +x ${GODOT_EDITOR}

          GODOT_VERSION=$(${GODOT_EDITOR} --version | sed 's///')
          TEMPLATE_DIR='${TEMPLATE_DIR}/${GODOT_VERSION}'
          mkdir -p ${TEMPLATE_DIR}
          echo ${GODOT_VERSION} > '${TEMPLATE_DIR}/version.txt'

          echo 'Export Templates directory path: ${TEMPLATE_DIR}'
          for file in *template*; do \
            new_name=$( echo ${file}  | sed 's/\(godot.\|.double\|.template\|.llvm\)//g' \
              | sed 's/linuxbsd/linux/;s/.console/_console/' \
              | sed 's/\(windows_[a-z]*\)\./\1_/' ) \
              && echo Installing ${new_name} \
              && mv ${file} ${TEMPLATE_DIR}/${new_name} \
          done
          echo 'Export Templates installed!'

          mkdir -p ${BIN}
          mkdir -p '~/src'

      - name: Checkout  
        uses: actions/checkout@v4
        with:
          path: '~/src'

      - name: Test
        run: |
          ls -a .
          ls -a v-sekai-world
          ls -a '~/.local/share/godot/export_templates/'

      - name: Build
        run: |
          for PLATFORM in ${BUILD_PLATFORMS}; do \
            echo 'Building ${PLATFORM}...'
            ${GODOT_EDITOR} ${BUILD_ARGS} --path '~/src' --export-release ${PLATFORM} ${BIN} \
          done

  build:
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      actions: write
    steps:
      - name: Build
        run: |
          ls .


