name: Build Platform Target

on:
  push:
    branches: [action]
env:
  BIN: 'release/bin/'
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout
        run: |
          mkdir -p src
          curl https://github.com/V-Sekai/world-godot/releases/latest/download/v-sekai-world.zip

      - name: Checkout  
        uses: actions/checkout@v4
        with:
          path: 'src'
          
      - name: Download Godot
        uses: actions/download-artifact@v4
        with:
          repository: V-Sekai/world-godot
          github-token: ${{ secrets.TOKEN_PAT2 }}
          
      - name: Checkout
        run: |
          ls -a .
