name: Build Platform Target

on:
  push:
    branches: [gh-test]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Set env
        run: |
          echo "GITHUB_REV=${{ github.event.sha }}" >> "$GITHUB_ENV"

      - name: Test
        run: |
          echo "Github event -  ${GITHUB_REV}"
