name: pre-commit

on:
  pull_request:
  push:
    branches:
      - lint

jobs:
  pre-commit-checks:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: pre-commit
        run: |
          bash .github/workflows/lint2.sh
     # - name: Install pre-commit
     #   run: pip install pre-commit

     # - name: Run pre-commit
     #   run: pre-commit run --all-files
