name: Squash
on:
  push:
    branches: [xr2]
permissions:
  contents: write
jobs:
  dispatch:
    name: Dispatch
    env:
     # GITHUB_TOKEN: ${{ secrets.SQUASH1 }}
      INPUT_REPO_TOKEN: GITHUB_TOKEN
      INPUT_BRANCH: main
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['dragonhunt02/godot']
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          ref: rx-assert
          #prop-upload
          fetch-depth: 0
      - name: Dispatch to workflow 
        run: |
            sudo apt install -y tree
            git status

            #pip install "gdtoolkit==4.*"
            #gdformat addons/network_manager/network_replication_manager.gd

            git log -n 5
            #git reset --soft HEAD~2  
            #git reset --hard HEAD~1  
            #rm CODEBASE.md
            #git add CODEBASE.md
            #git rebase --onto origin/rx HEAD~1 HEAD

            REPL='	if not VSKUtils.assert_exists(get_tree()):'
            REPL="$REPL"$'\n''		return'
            echo "$REPL"

            find . -type f -name '*.gd' -exec sed -i 's/^\t+assert(get_tree())$/'"$REPL"'/g' {} +
            
            #Reset and apply
            #git diff HEAD~1 HEAD > ../last.patch
            #rm -rf *
            #git reset --hard origin/rx-origin
            #git apply --index ../last.patch
            
            #git restore --source=origin/rx -- addons/vsk_game_framework/scenes/import/
            #git restore --source=origin/rx -- addons/vsk_game_framework/textures/
            #git restore --source=origin/rx -- addons/vsk_game_framework/animations/
            #git restore --source=origin/rx -- addons/textureRectUrl/
            #git restore --source=origin/rx -- addons/godot-xr-tools/
            #git restore --source=origin/rx -- addons/vsk_ui/fonts/
            #git restore --source=origin/rx -- addons/vsk_ui/icons/
            #git restore --source=origin/rx -- vsk_default/example_ugc/
            #git restore --source=origin/rx -- spash.png
            #git add spash.png
            # rm spash.png
            # git lfs pull origin rx
            # git checkout HEAD~1 -- spash.png
            # git add --renormalize spash.png
            GITLS='
            git ls-files -z addons/vsk_game_framework/scenes/import/ | xargs -0 git update-index --skip-worktree
            git ls-files -z addons/vsk_game_framework/textures/ | xargs -0 git update-index --skip-worktree
            git ls-files -z addons/vsk_game_framework/animations/ | xargs -0 git update-index --skip-worktree
            git ls-files -z addons/textureRectUrl/ | xargs -0 git update-index --skip-worktree
            git ls-files -z addons/godot-xr-tools/ | xargs -0 git update-index --skip-worktree
            git ls-files -z addons/vsk_ui/fonts/ | xargs -0 git update-index --skip-worktree
            git ls-files -z addons/vsk_ui/icons/ | xargs -0 git update-index --skip-worktree
            git ls-files -z spash.png | xargs -0 git update-index --skip-worktree
            #git ls-files -z vsk_default/example_ugc/ | xargs -0 git update-index --skip-worktree
            git update-index --skip-worktree vsk_default/example_ugc/maps/cc0_hut/*.png
            git update-index --skip-worktree vsk_default/example_ugc/maps/cc0_hut/*.res
            git update-index --skip-worktree vsk_default/example_ugc/maps/cc0_hut/*.bin
            git update-index --skip-worktree vsk_default/example_ugc/maps/cc0_hut/*.unwrap_cache
            '

            #######find . -type f -name "*.gd" -exec sed -i -e 's/assert\(()\)/push_error/g' {} +
            #find . -type f -name "*.gd" -exec sed -i -e 's/\(\t*\)assert(false, \(.*\))/\1push_error(\2)\n\1return/g' {} +
            #find . -type f -name "*.gd" -exec sed -i -e 's/\(\t*\)assert(\(.*\) == OK)/\1if \(\2 != OK\):\n\1\tpush_error\(\)\n\1\treturn/g' {} +
            git config --global user.email "jackhunt43@libero.it"
            git config --global user.name "dragonhunt02"
            git add -A
            #git commit -a -m 'Implement prop validation, sanitisation and in-editor upload'
            git commit -a -m 'Replace assert get_tree'
            git log -n 5
            git status
            git diff
            #git diff origin/rx-origin
            #git push -f
            exit 1


            #sha256sum "addons/godot-xr-tools-slim/hands/animations/left/Grip 2.res"
            #sha256sum "addons/godot-xr-tools/hands/animations/left/Grip 2.res"

            #diff -rs addons/godot-xr-tools-slim/ addons/godot-xr-tools/
            #exit 1

            
            #git switch origin/xr1
            git log

            DIR="temp"
            DIR2="godot-xr-tools-slim/"
            mkdir -p $DIR 

            tar cvf - addons/godot-xr-tools/hands/model/hand_r.gltf* | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/hands/model/hand_l.gltf* | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/hands/materials/cleaning_glove.material | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/hands/materials/labglove.material | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/assets/hand.gd* | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/editor/icons/hand.svg* | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/hands/animations/* | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/hands/scenes/highpoly/right_fullglove_hand.tscn | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/hands/scenes/highpoly/left_fullglove_hand.tscn | tar xvf - -C $DIR

            tar cvf - addons/godot-xr-tools/hands/textures/* | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/LICENSE | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/VERSIONS.md | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/CONTRIBUTORS.md | tar xvf - -C $DIR


            mv temp/addons/godot-xr-tools/ addons/$DIR2
            rm -rf temp
            rm -rf addons/godot-xr-tools/
            mv -v addons/$DIR2 addons/godot-xr-tools/
            cd addons/
            tree godot-xr-tools
            
            git status
            git log
            git config --global user.email "jackhunt43@libero.it"
            git config --global user.name "dragonhunt02"
            git add -A
            git commit -a -m 'Remove unused stale Godot XR Tools code'
            git log
            git status
            #git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ matrix.repo }}.git
            git push
