name: Squash
on:
  push:
    branches: [xr2]
permissions:
  contents: write
jobs:
  dispatch:
    name: Dispatch
    env:
     # GITHUB_TOKEN: ${{ secrets.SQUASH1 }}
      INPUT_REPO_TOKEN: GITHUB_TOKEN
      INPUT_BRANCH: main
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['dragonhunt02/godot']
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          ref: assert-fix
          fetch-depth: 3
      - name: Dispatch to workflow 
        run: |
            sudo apt install -y tree
            git status

            git log

            #find . -type f -name "*.gd" -exec sed -i -e 's/assert\(()\)/push_error/g' {} +
            find . -type f -name "*.gd" -exec sed -i -e 's/\(\t*\)assert(false, \(.*\))/\1push_error(\2)\n\1return/g' {} +
            find . -type f -name "*.gd" -exec sed -i -e 's/\(\t*\)assert(\(.*\) == OK)/\1if \(\2 != OK\):\n\1\tpush_error\(\)\n\1\treturn/g' {} +
            git config --global user.email "jackhunt43@libero.it"
            git config --global user.name "dragonhunt02"
            git add -A
            git commit -a -m 'Replace assert statements'
            git log
            git status
            #git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ matrix.repo }}.git
            git push
            exit 1


            #sha256sum "addons/godot-xr-tools-slim/hands/animations/left/Grip 2.res"
            #sha256sum "addons/godot-xr-tools/hands/animations/left/Grip 2.res"

            #diff -rs addons/godot-xr-tools-slim/ addons/godot-xr-tools/
            #exit 1

            
            #git switch origin/xr1
            git log

            DIR="temp"
            DIR2="godot-xr-tools-slim/"
            mkdir -p $DIR 

            tar cvf - addons/godot-xr-tools/hands/model/hand_r.gltf* | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/hands/model/hand_l.gltf* | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/hands/materials/cleaning_glove.material | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/hands/materials/labglove.material | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/assets/hand.gd* | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/editor/icons/hand.svg* | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/hands/animations/* | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/hands/scenes/highpoly/right_fullglove_hand.tscn | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/hands/scenes/highpoly/left_fullglove_hand.tscn | tar xvf - -C $DIR

            tar cvf - addons/godot-xr-tools/hands/textures/* | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/LICENSE | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/VERSIONS.md | tar xvf - -C $DIR
            tar cvf - addons/godot-xr-tools/CONTRIBUTORS.md | tar xvf - -C $DIR


            mv temp/addons/godot-xr-tools/ addons/$DIR2
            rm -rf temp
            rm -rf addons/godot-xr-tools/
            mv -v addons/$DIR2 addons/godot-xr-tools/
            cd addons/
            tree godot-xr-tools
            
            git status
            git log
            git config --global user.email "jackhunt43@libero.it"
            git config --global user.name "dragonhunt02"
            git add -A
            git commit -a -m 'Remove unused stale Godot XR Tools code'
            git log
            git status
            #git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ matrix.repo }}.git
            git push
